# Generated by Django 2.2 on 2023-07-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_ytlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ytlink',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
