# Generated by Django 2.2 on 2023-07-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230710_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='loc',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
