# Generated by Django 2.2 on 2023-07-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_products_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='loc',
            field=models.CharField(default='location', max_length=250),
        ),
    ]
